services:
  # 1. Base de Datos (Usa variables del .env)
  db:
    image: postgres:15
    container_name: timetrack_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}         
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: timetrack_redis
    ports:
      - "6379:6379"

  auth-ms:
    build: ./microservices/auth-ms
    container_name: auth_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./microservices/auth-ms:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=auth_db  
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  patients-ms:
    build: ./microservices/patients-ms
    container_name: patients_service
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./microservices/patients-ms:/app
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/patients_db

  professionals-ms:
    build: ./microservices/professionals-ms
    container_name: professionals_service
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./microservices/professionals-ms:/app
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/professionals_db

  schedule-ms:
    build: ./microservices/schedule-ms
    container_name: schedule_service
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ./microservices/schedule-ms:/app
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/schedule_db

  appointments-ms:
    build: ./microservices/appointments-ms
    container_name: appointments_service
    command: python manage.py runserver 0.0.0.0:8004
    volumes:
      - ./microservices/appointments-ms:/app
    ports:
      - "8004:8004"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/appointments_db

  notification-ms:
    build: ./microservices/notification-ms
    container_name: notification_service
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - ./microservices/notification-ms:/app
    ports:
      - "8005:8005"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/notifications_db

  ia-ms:
    build: ./microservices/ia-ms
    container_name: ia_service
    command: python manage.py runserver 0.0.0.0:8006
    volumes:
      - ./microservices/ia-ms:/app
    ports:
      - "8006:8006"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/ia_db

  portal-ms:
    build: ./microservices/portal-ms
    container_name: portal_service
    command: python manage.py runserver 0.0.0.0:8007
    volumes:
      - ./microservices/portal-ms:/app
      - media_portal_data:/app/media
    ports:
      - "8007:8007"
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/portal_db

  gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - auth-ms

  frontend:
    build: ./frontend
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - gateway

volumes:
  postgres_data:
  media_portal_data: