[tool.ruff]
# Excluir carpetas comunes
exclude = [
    ".bzr", ".direnv", ".eggs", ".git", ".hg", ".mypy_cache", ".nox", ".pants.d",
    ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", "__pypackages__", "_build",
    "buck-out", "build", "dist", "node_modules", "venv", "**/migrations/*.py"
]
# Mantenemos el l√≠mite de 120 caracteres
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E722"]

# --- AGREGAR ESTO ---
# Esto fuerza a Ruff a tratar estas carpetas como "Locales" tanto en tu PC como en GitHub
[tool.ruff.lint.isort]
known-first-party = [
    "users",            # Auth-MS
    "core",             # Settings de todos
    "gestion_citas",    # Appointments-MS
    "patients",         # Patients-MS
    "staff",            # Professionals-MS
    "agenda",           # Schedule-MS
    "content", "forms", # Portal-MS
    "comunicaciones",   # Notification-MS
    "agent"             # IA-MS
]